results = calcMSISCE('./example_data', ...
    'FilePattern', 'sub_*.mat', ...
    'SampleRate', 1000, ...
    'Channels', 63, ...
    'FrequencyRange', 1:30, ...
    'Threshold', 1.2, ...
    'UseCSD', false, ...
    'SaveResults', false, ...
    'Verbose', true);

figure;
plot(results.frequencies, squeeze(results.MSI(1,1,:)), 'LineWidth', 2);
xlabel('Frequency (Hz)');
ylabel('MSI');
title('Example MSI spectrum');

figure;
plot(results.frequencies, squeeze(results.meanSCE(1,1,:)), 'LineWidth', 2);
xlabel('Frequency (Hz)');
ylabel('Mean normalized SCE');
title('Example SCE spectrum');
